### PR TITLE
Add option to build examples through CMake

### PR DESCRIPTION
**Pull request by LawG4**
Supplied as a submodule is a set of cmake toolchain files, which when combined together allow a user to build through cmake. Supply a CMakeList.txt for each example using said toolchain

Toolchain instructions are in the readme.

Also moved a couple examples up a directory, it seems initiallty they were put in a topic folder, with more to come, but they ended up being the only example in that folder. ie network/sockettest -> network/

### CODE REVIEW

**Comment by fincs** [comment]
You might be interested to know that devkitPro is [already working on bringing up official CMake support](https://github.com/devkitPro/pacman-packages/tree/master/cmake) for the various platforms we target. Currently 3DS, Switch and Wii U are fully supported, while the rest of the platforms will continue to be added. For this reason, I'd advise you to wait a bit longer and stay tuned.

**Comment by LawG4** [comment]
Hia,

Thanks for taking a look at this, I could aim to transfer my ppc toolchain into something compatible with the official repo and create a pull request there.

Before starting with something like that, I was curious about how the ppc toolchains would work? My aim with my ppc toolchain is to allow builds on windows outside the msys2 environment to speed things up, and add better ide integration on windows. Is this something the dkp cmake would want, or does the distribution through dkp-pacman limit this?

**Comment by WinterMute** [comment]
@LawG4 Part of the point of our toolchain infrastructure is to maintain as much as possible of the build environment across host OSes. We do this so that a well constructed project can build OOB regardless of windows/macOS/linux as well as take advantage of the ease of installation of many libraries useful for porting. The portlib setup currently requires the filesystem root to be at `/opt/devkitpro` since many libraries embed install paths within compiled binaries and scripts. This basically requires msys2 on windows (which is, in any case, required in order to obtain pacman for package installation) so we would be incredibly reluctant to accept anything that impacts on the portability of our infrastructure. One of the goals of devkitPro is to encourage people to ensure their projects build everywhere and aren't dependent on the idiosyncrasies of any particular host OS or IDE. Ultimately cross platform portability is probably the most important aspect of our philosophy. Distribution through (dkp-)pacman is something we do in order to provide, support and encourage that portability. Attempting to enable building outside the msys2 environment is likely to have a detrimental impact on the infrastructure we provide.

**Comment by LawG4** [comment]
Hi @WinterMute,

Thanks for the explanation of the methodology, I think I should have specified that the aim was to make it work outside of msys2 *as well* The problem with cmake builds only working within msys2 is that they can't be imported into text editors because include paths point to `opt/devkitpro` instead` C:/devkitPro` 

I think the changes shouldn't effect things outside of msys2, but I'll have a look and see how it goes. Ideally I'd to be able to build inside QtCreator.

**Comment by fincs** [comment]
On Windows, the only CMake binary we support is the one that ships with msys2 as a pacman package. It might be worth investigating if the IDEs you're using can be pointed to use the right CMake binary.

**Comment by LawG4** [comment]
Okay, thank you! I'll give that a try, are there any examples with a cmake build system in place, I couldn't find one inside the pacman packages?

**Comment by WinterMute** [comment]
> Okay, thank you! I'll give that a try, are there any examples with a cmake build system in place, I couldn't find one inside the pacman packages?

Not yet. As @fincs said - stay tuned. In the meantime I'd be really grateful if you removed your cmake machinery & the wii examples fork from public view - these things have an unfortunate habit of propagating & causing us major support issues later.

We may need to have a discussion in private regarding your expectations of how things should work with qtCreator. Subverting build infrastructure to use different paths isn't really something we want to see happening. It may seem more convenient for you but we know from experience that one project's convenience can lead to major issues for others.

**Comment by LawG4** [comment]
Those should hidden now, let me know where the best place to begin the discussion would be

**Pull request closed without merging**
